// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiVetenary.Data.Models
{
    public partial class AppointmentDetail
    {
        public int AppointmentDetailId { get; set; }
        public int? AppointmentId { get; set; }
        public int? AnimalId { get; set; }
        public int? VeterinarianId { get; set; }
        public int? ServiceId { get; set; }
        public DateTime? ServiceDate { get; set; }
        public TimeSpan? ServiceTime { get; set; }
        public string Status { get; set; }
        public string Notes { get; set; }
        public int? ServiceDuration { get; set; }
        public decimal? ServiceCost { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }

        public virtual Animal Animal { get; set; }
        public virtual Appointment Appointment { get; set; }
        public virtual Service Service { get; set; }
        public virtual Veterinarian Veterinarian { get; set; }
    }
}